### PR TITLE
Attributes form: Switch to model-based tree views in vector layer properties

### LINKED ISSUE #37038: Keep order when drag and drop multiple widget
In layer properties --> attributes form -->  drag and drop designer, drag and dropping a selection of several widgets invert their order. 
The first widget dragged becomes the last dropped and vice versa. 
It would be more convenient to keep the order.

Tested with QGIS 3.12.3

### LINKED ISSUE #49502: New actions are not available in edit form tab until properties dialog reopening
### What is the bug or the crash?

Before you can reuse action you create in a drag-and-drop form editor, you need to reopen the Layer properties dialog. Just pressing "Apply" after actions creation is not enough.

### Steps to reproduce the issue

Take a layer properties > Attributes Form > drag-and-drop mode
In a vector layer Actions tab, add new actions (e.g. with "create default actions")
Press Apply
Enable Attributes Form tab. No action is available in the Actions drop-down list.
Close and reopen the dialog. Here they are.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.26.0-Buenos Aires | QGIS code revision | 0aece2818e
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.3.2
PROJ version | 8.1.1
EPSG Registry database version | v10.028 (2021-07-07)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.11.5
OS version | macOS 12.4
  |   |   |  
Active Python plugins
processing | 2.12.99
sagaprovider | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.6

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by gacarrillor**
Initial work packages of the [QEP Overview of widget types while configuring forms](https://github.com/qgis/QGIS-Enhancement-Proposals/pull/318
).

We preserved the look and feel as well as the prior behavior, while doing small refactorings and improving minor UI/UX issues.

Based on the new model/view approach this PR introduces a new feature:

[FEATURE] Allow users to switch between field names and field aliases in the Form Layout panel.

https://github.com/user-attachments/assets/4039587a-281e-40f3-a690-705254f59d88

-------

Fix #37038
Fix #49502

Funded by the [QGIS user group Switzerland](https://qgis.ch/).

### CODE REVIEW

File: src/gui/vector/qgsattributesformmodel.h [hunk 1]
```diff
@@ -0,0 +1,459 @@
...
+
+#include "qgsattributeeditorelement.h"
+#include "qgsoptionalexpression.h"
+#include "qgsvectorlayer.h"
+
+#include <QAbstractItemModel>
+#include <QPushButton>
+
+
+class QgsAttributeFormTreeData
```
Comment (gacarrillor) [inline src/gui/vector/qgsattributesformmodel.h]: All the enums/classes/structs inside this class were moved from `qgsattributesformproperties.h`

To keep them under a shared namespace, I created this `QgsAttributeFormTreeData` 'container' class. Not sure if it's the recommended way of doing it, though.

File: src/gui/vector/qgsattributesformmodel.h [hunk 2]
```diff
@@ -0,0 +1,459 @@
...
+        SpacerElementEditorConfiguration mSpacerElementEditorConfiguration;
+        QColor mBackgroundColor;
+        bool mCollapsed = false;
+        QgsOptionalExpression mCollapsedExpression;
+        QgsAttributeEditorElement::LabelStyle mLabelStyle;
+    };
+};
+
+
+class AttributeFormTreeItem
```
Comment (gacarrillor) [inline src/gui/vector/qgsattributesformmodel.h]: We'll be relying on this `AttributeFormTreeItem` to hold the underlying parent-child relationships between items/nodes.

File: src/gui/vector/qgsattributesformmodel.h [hunk 3]
```diff
@@ -0,0 +1,459 @@
...
+
+    QgsAttributeFormTreeData::DnDTreeItemData mItemData;
+    QgsAttributeFormTreeData::FieldConfig mFieldConfigData;
+    QString mFieldNameData;
+
+    AttributeFormTreeItem *mParent;
+};
+
+
+class QgsAttributesAvailableWidgetsModel : public QAbstractItemModel
```
Comment (gacarrillor) [inline src/gui/vector/qgsattributesformmodel.h]: I can imagine we'll be able to have an abstract class inheriting from `QAbstractItemModel` and two subclasses of that abstract class, one for `Available Widgets` and one for `Form Layout`. However, I'm not there yet.

**Comment by gacarrillor** [comment]
@nirvn, this is the current status of this work.

We've migrated the Available Widgets panel to a model-based tree view and it's currently loading, reflecting the look-and-feel (icons, tooltips), and supporting some behavior already (showing the third panel each time we select a single row in the panel, storing the changes when we switch to another row or to another tab in the Vector Layer Properties dialog, and also applying the changes to the layer).

The code is not yet clean, since I haven't added proper documentation for new classes/methods and there's a lot of commented code to make it compile.

If you see some flaws, please let me know.

**Comment by gacarrillor** [comment]
@nirvn, update status:

Switching to a model-based view is going well. As far as I can see, the only pending thing is the serialization of Form Layout nodes (including their children) for the drag and drop. Other than that, I think we're ready for a first review when you have the time for it 🙏🏽 

I could be pushing other minor tweaks and perhaps the switching from names to aliases, which should be already possible with the current state of this work.

Denis would like first to have a review for this PR before I start adding unit tests.

File: src/gui/vector/qgsattributesformmodel.h [hunk 4]
```diff
@@ -0,0 +1,738 @@
...
+    {
+      Field,
+      Relation,
+      Container, //!< Container for the form
+      QmlWidget,
+      HtmlWidget,
+      WidgetType,   //!< In the available widgets tree, the type of widget
+      Action,       //!< Layer action
+      TextWidget,   //!< Text widget type, \since QGIS 3.30
+      SpacerWidget, //!< Spacer widget type, \since QGIS 3.30
```
Comment (nirvn) [inline src/gui/vector/qgsattributesformmodel.h]: Can we add descriptions for all items in there, and vertically align the //!< block

File: src/gui/vector/qgsattributesformmodel.h [hunk 5]
```diff
@@ -0,0 +1,738 @@
...
+    };
+
+    /**
+     * \brief Main class to store and transfer editor data contained within a QgsAttributesFormModel.
+     *
+     * \ingroup gui
+     * \note Prior to QGIS 3.44 this was available as QgsAttributesFormProperties::DnDTreeItemData
+     * \since QGIS 3.44
+     */
+    class DnDTreeNodeData
```
Comment (nirvn) [inline src/gui/vector/qgsattributesformmodel.h]: Can we come up with a better name here? For e.g., the use of 'node' isn't super great here (maybe it's because I've spent too much time with blender :) ). I feel like 'item' would be a better keyword to use.

Also, this is used in more ways that just through the drag and drop designer right? I'd remove the DnD reference if that's the case.

AttributeFormItemData ?

File: src/gui/vector/qgsattributesformmodel.h [hunk 6]
```diff
@@ -0,0 +1,738 @@
...
+
+    int rowCount( const QModelIndex &parent = QModelIndex() ) const override;
+    int columnCount( const QModelIndex &parent = QModelIndex() ) const override;
+
+    // Drag and drop support (common methods)
+    QStringList mimeTypes() const override;
+    QMimeData *mimeData( const QModelIndexList &indexes ) const override;
+
+    // Other methods
+    /**
```
Comment (nirvn) [inline src/gui/vector/qgsattributesformmodel.h]: Needs cleaning up

File: src/gui/vector/qgsattributesformmodel.h [hunk 7]
```diff
@@ -0,0 +1,738 @@
...
+    ~QgsAttributesFormModel() override;
+
+    // Basic functionality
+    QModelIndex index( int row, int column, const QModelIndex &parent = QModelIndex() ) const override;
+    QModelIndex parent( const QModelIndex &index ) const override;
+
+    int rowCount( const QModelIndex &parent = QModelIndex() ) const override;
+    int columnCount( const QModelIndex &parent = QModelIndex() ) const override;
+
+    // Drag and drop support (common methods)
```
Comment (nirvn) [inline src/gui/vector/qgsattributesformmodel.h]:
```suggestion
```

File: src/gui/vector/qgsattributesformmodel.h [hunk 8]
```diff
@@ -0,0 +1,738 @@
...
+  protected:
+    /**
+     * Returns the underlying node that corresponds to the given \a index.
+     *
+     * If the given \a index is not valid the root node is returned.
+     */
+    QgsAttributesFormTreeNode *nodeForIndex( const QModelIndex &index ) const;
+
+    std::unique_ptr< QgsAttributesFormTreeNode > mRootNode;
+    QgsVectorLayer *mLayer;
```
Comment (nirvn) [inline src/gui/vector/qgsattributesformmodel.h]: private?

File: src/gui/vector/qgsattributesformmodel.h [hunk 9]
```diff
@@ -0,0 +1,738 @@
...
+
+
+/**
+ * \brief Class to hold parent-child relations as well as node data contained within a QgsAttributesFormModel.
+ *
+ * \warning Not part of stable API and may change in future QGIS releases.
+ * \ingroup gui
+ * \since QGIS 3.44
+ */
+class GUI_EXPORT QgsAttributesFormTreeNode
```
Comment (nirvn) [inline src/gui/vector/qgsattributesformmodel.h]: I'd avoid the use of tree and node throughout. 

We have a model, and we have items, that feels more inline with what we have in QGIS / Qt.

```suggestion
class GUI_EXPORT QgsAttributesFormItem
```

File: src/gui/vector/qgsattributesformmodel.h [hunk 10]
```diff
@@ -0,0 +1,738 @@
...
+
+    /**
+     * Stores a data \a value in a given \a role inside the current node.
+     */
+    bool setData( int role, const QVariant &value );
+
+    /**
+     * Appends a \a child to this node. Takes ownership of the child.
+     */
+    void addChildNode( std::unique_ptr< QgsAttributesFormTreeNode > &&child );
```
Comment (nirvn) [inline src/gui/vector/qgsattributesformmodel.h]:
```suggestion
    void addChild std::unique_ptr< QgsAttributesFormTreeNode > &&item );
```

File: src/gui/vector/qgsattributesformmodel.h [hunk 11]
```diff
@@ -0,0 +1,738 @@
...
+
+    /**
+     * Inserts a child \a node to the current node at a given \a position. Takes ownership of the child node.
+     */
+    void insertChildNode( int position, std::unique_ptr< QgsAttributesFormTreeNode > &&node );
```
Comment (nirvn) [inline src/gui/vector/qgsattributesformmodel.h]:
```suggestion
    void insertChild int position, std::unique_ptr< QgsAttributesFormTreeNode > &&item );
```

File: src/gui/vector/qgsattributesformmodel.h [hunk 12]
```diff
@@ -0,0 +1,738 @@
...
+     */
+    void setIcon( const QIcon &icon ) { mIcon = icon; }
+
+  private:
+    QString mName = QString();
+    QString mDisplayName = QString();
+    QIcon mIcon;
+    QgsAttributesFormTreeData::AttributesFormTreeNodeType mNodeType = QgsAttributesFormTreeData::Field;
+    QString mNodeId = QString();
+    QgsAttributesFormTreeData::DnDTreeNodeData mNodeData;
```
Comment (nirvn) [inline src/gui/vector/qgsattributesformmodel.h]: mNodeId -> mId

mNodeData -> mData

Basically, kill references to nodes :)

File: src/gui/vector/qgsattributesformmodel.h [hunk 13]
```diff
@@ -0,0 +1,738 @@
...
+     */
+    void deleteChildAtIndex( int index );
+
+    /**
+     * Deletes all child nodes from this node.
+     */
+    void deleteChildren();
+
+    /**
+     * Returns the type of the current node.
```
Comment (nirvn) [inline src/gui/vector/qgsattributesformmodel.h]: I think "current" isn't needed here. This the type of the item, full stop.

File: src/gui/vector/qgsattributesformmodel.cpp [hunk 14]
```diff
@@ -0,0 +1,1162 @@
...
+#include "qgseditorwidgetregistry.h"
+#include "qgsattributeeditoraction.h"
+#include "qgsattributeeditorcontainer.h"
+#include "qgsattributeeditorrelation.h"
+#include "qgsattributeeditorqmlelement.h"
+#include "qgsattributeeditorhtmlelement.h"
+#include "qgsattributeeditortextelement.h"
+#include "qgsattributeeditorspacerelement.h"
+
+#include "QMimeData"
```
Comment (nirvn) [inline src/gui/vector/qgsattributesformmodel.cpp]:
```suggestion
#include <QMimeData>
```

File: src/gui/vector/qgsattributesformmodel.cpp [hunk 15]
```diff
@@ -0,0 +1,1162 @@
...
+
+/*
+ * FieldConfig implementation
+ */
```
Comment (nirvn) [inline src/gui/vector/qgsattributesformmodel.cpp]: I don't think we usually do block comment separators in our .cpp files.

File: src/gui/vector/qgsattributesformmodel.cpp [hunk 16]
```diff
@@ -0,0 +1,1162 @@
...
+QgsAttributesFormTreeData::FieldConfig::FieldConfig( QgsVectorLayer *layer, int idx )
+{
+  mAlias = layer->fields().at( idx ).alias();
```
Comment (nirvn) [inline src/gui/vector/qgsattributesformmodel.cpp:38]: Do we want a null check and a field index check here just in case?

File: src/gui/vector/qgsattributesformmodel.cpp [hunk 17]
```diff
@@ -0,0 +1,1162 @@
...
+}
+
+void QgsAttributesFormTreeData::DnDTreeNodeData::setTextElementEditorConfiguration( const QgsAttributesFormTreeData::TextElementEditorConfiguration &textElementEditorConfiguration )
+{
+  mTextElementEditorConfiguration = textElementEditorConfiguration;
+}
+
+//
+// QgsAttributesFormTreeNode implementation
+//
```
Comment (nirvn) [inline src/gui/vector/qgsattributesformmodel.cpp]: Mix of
/*
 *
 */

and
//
//
//

We'd need to fix that, but I think we just want them out :)

File: src/gui/vector/qgsattributesformmodel.cpp [hunk 18]
```diff
@@ -0,0 +1,1162 @@
...
+        return node;
+    }
+  }
+
+  return nullptr;
+}
+
+int QgsAttributesFormTreeNode::childCount() const
+{
+  return int( mChildren.size() );
```
Comment (nirvn) [inline src/gui/vector/qgsattributesformmodel.cpp]: I think we prefer the following:

`static_cast<int>( mChildren.size() );`

File: src/gui/vector/qgsattributesformmodel.cpp [hunk 19]
```diff
@@ -0,0 +1,1162 @@
...
+  if ( !mParent )
+    return 0;
+
+  const auto it = std::find_if( mParent->mChildren.cbegin(), mParent->mChildren.cend(), [this]( const std::unique_ptr< QgsAttributesFormTreeNode > &treeNode ) {
+    return treeNode.get() == this;
+  } );
+
+  if ( it != mParent->mChildren.cend() )
+    return ( int ) std::distance( mParent->mChildren.cbegin(), it );
+  return -1;
```
Comment (nirvn) [inline src/gui/vector/qgsattributesformmodel.cpp]: static_cast + I'd use {} to increase readability.

File: src/gui/vector/qgsattributesformmodel.cpp [hunk 20]
```diff
@@ -0,0 +1,1162 @@
...
+    return 0;
+
+  const QgsAttributesFormTreeNode *parentNode = nodeForIndex( parent );
+
+  return parentNode ? parentNode->childCount() : 0;
+}
+
+int QgsAttributesFormModel::columnCount( const QModelIndex &parent ) const
+{
+  Q_UNUSED( parent );
```
Comment (nirvn) [inline src/gui/vector/qgsattributesformmodel.cpp]:
```suggestion
int QgsAttributesFormModel::columnCount( const QModelIndex & ) const
{
```

File: src/gui/vector/qgsattributesformmodel.cpp [hunk 21]
```diff
@@ -0,0 +1,1162 @@
...
+{
+  if ( !hasIndex( row, column, parent ) )
+    return QModelIndex();
+
+  QgsAttributesFormTreeNode *parentNode = nodeForIndex( parent );
+  if ( !parentNode )
+    return QModelIndex();
+
+  if ( QgsAttributesFormTreeNode *childNode = parentNode->child( row ) )
+    return createIndex( row, column, childNode );
```
Comment (nirvn) [inline src/gui/vector/qgsattributesformmodel.cpp]: isn't this supposed to be the parentNode here?

File: src/gui/vector/qgsattributesformmodel.cpp [hunk 22]
```diff
@@ -0,0 +1,1162 @@
...
+  Q_UNUSED( section )
+  return orientation == Qt::Horizontal && role == Qt::DisplayRole ? tr( "Available Widgets" ) : QVariant {};
+}
+
+void QgsAttributesAvailableWidgetsModel::populate()
+{
+  beginResetModel();
+  mRootNode->deleteChildren();
+
+  // load Fields
```
Comment (nirvn) [inline src/gui/vector/qgsattributesformmodel.cpp]: Please harmonize capitalization throughout this function. My preference: Load fields

File: src/gui/vector/qgsattributesformmodel.cpp [hunk 23]
```diff
@@ -0,0 +1,1162 @@
...
+
+  auto itemFields = std::make_unique< QgsAttributesFormTreeNode >( QgsAttributesFormTreeData::WidgetType, QStringLiteral( "Fields" ) );
+
+  const QgsFields fields = mLayer->fields();
+  for ( int i = 0; i < fields.size(); ++i )
+  {
+    const QgsField field = fields.at( i );
+    auto itemData = QgsAttributesFormTreeData::DnDTreeNodeData();
```
Comment (nirvn) [inline src/gui/vector/qgsattributesformmodel.cpp]: A great example of why I dislike the DnD reference here :)

File: src/gui/vector/qgsattributesformmodel.cpp [hunk 24]
```diff
@@ -0,0 +1,1162 @@
...
+      itemAction->setData( NodeNameRole, actionTitle );
+      itemAction->setData( NodeDataRole, itemData );
+
+      itemActions->addChildNode( std::move( itemAction ) );
+    }
+  }
+
+  mRootNode->addChildNode( std::move( itemActions ) );
+
+  // QML/HTML widgets
```
Comment (nirvn) [inline src/gui/vector/qgsattributesformmodel.cpp]:
```suggestion
  // Other widgets
```

File: src/gui/vector/qgsattributesformmodel.cpp [hunk 25]
```diff
@@ -0,0 +1,1162 @@
...
+  itemTextData.setShowLabel( true );
+  auto itemText = std::make_unique< QgsAttributesFormTreeNode >( QgsAttributesFormTreeData::TextWidget, itemTextData, QStringLiteral( "Text Widget" ), tr( "Text Widget" ) );
+  itemOtherWidgets->addChildNode( std::move( itemText ) );
+
+  QgsAttributesFormTreeData::DnDTreeNodeData itemSpacerData = QgsAttributesFormTreeData::DnDTreeNodeData();
+  itemTextData.setShowLabel( false );
+  auto itemSpacer = std::make_unique< QgsAttributesFormTreeNode >( QgsAttributesFormTreeData::SpacerWidget, QStringLiteral( "Spacer Widget" ), tr( "Spacer Widget" ) );
+  itemOtherWidgets->addChildNode( std::move( itemSpacer ) );
+
+  mRootNode->addChildNode( std::move( itemOtherWidgets ) );
```
Comment (nirvn) [inline src/gui/vector/qgsattributesformmodel.cpp]: Mixing item and node here :) get rid of 'node' throughout (mentioned in the .h[eader] already)

File: src/gui/vector/qgsattributesformmodel.cpp [hunk 26]
```diff
@@ -0,0 +1,1162 @@
...
+      return QVariant();
+    }
+
+    case Qt::DecorationRole:
+      return node->icon();
+
+    case Qt::BackgroundRole:
+    {
+      if ( node->type() == QgsAttributesFormTreeData::AttributesFormTreeNodeType::WidgetType )
+        return QBrush( Qt::lightGray );
```
Comment (nirvn) [inline src/gui/vector/qgsattributesformmodel.cpp:695]: Note to self: this is not dark theme friendly, we can fix later.

File: src/gui/vector/qgsattributesformmodel.cpp [hunk 27]
```diff
@@ -0,0 +1,1162 @@
...
+
+Qt::DropActions QgsAttributesFormLayoutModel::supportedDropActions() const
+{
+  return Qt::DropAction::CopyAction | Qt::DropAction::MoveAction;
+}
+
+bool QgsAttributesFormLayoutModel::dropMimeData( const QMimeData *data, Qt::DropAction action, int row, int column, const QModelIndex &parent )
+{
+  Q_UNUSED( column )
+  bool bDropSuccessful = false;
```
Comment (nirvn) [inline src/gui/vector/qgsattributesformmodel.cpp]: What does b stand for in bDrop? I'd remove the b or expand into its full meaning :)

File: src/gui/attributeformconfig/qgsattributeformcontaineredit.h [hunk 28]
```diff
@@ -19,24 +19,38 @@
...
   public:
-    explicit QgsAttributeFormContainerEdit( QTreeWidgetItem *item, QgsVectorLayer *layer, QWidget *parent = nullptr );
+    explicit QgsAttributeFormContainerEdit( const QgsAttributesFormTreeData::DnDTreeNodeData &nodeData, QgsVectorLayer *layer, QWidget *parent = nullptr );
+
+    /**
+     * Sets the \a containerName.
+     *
+     * \since QGIS 3.44
+     */
+    void setTitle( const QString &containerName );
```
Comment (nirvn) [inline src/gui/attributeformconfig/qgsattributeformcontaineredit.h]: We should avoid referring to title vs name here.

```suggestion
    /**
     * Sets the container \a title.
     *
     * \since QGIS 3.44
     */
    void setTitle( const QString &title );
```

File: src/gui/attributeformconfig/qgsattributeformcontaineredit.h [hunk 29]
```diff
@@ -19,24 +19,38 @@
...
+
+    /**
+     * Sets up the container type comboBox based on the \a containerType and on whether it \a isTopLevelContainer.
```
Comment (nirvn) [inline src/gui/attributeformconfig/qgsattributeformcontaineredit.h]: So, beyond the type (comboBox), I feel like when we use \a to refer to parameter within a function description, it should mostly be reserved for instances where it reads like English (i.e. Sets the field \a name). Here it's not really the case, so I'd go for a list of \param

```suggestion
     * Sets up the container combo box based on its type and whether it is located at the top level.
       \param isTopLevelContainer container sitting at the top level
       \param containerType container type
```

File: src/gui/vector/qgsattributesformmodel.h [hunk 30]
```diff
@@ -0,0 +1,738 @@
...
+
+/**
+ * \brief Class to describe editor data contained within a QgsAttributesFormModel.
+ *
+ * \warning Not part of stable API and may change in future QGIS releases.
+ * \ingroup gui
+ * \note Prior to QGIS 3.44 this was available as QgsAttributesFormProperties
+ * \since QGIS 3.44
+ */
+class GUI_EXPORT QgsAttributesFormTreeData
```
Comment (nirvn) [inline src/gui/vector/qgsattributesformmodel.h]: Let's remove the tree reference.

```suggestion
class GUI_EXPORT QgsAttributesFormData
```

**Review by nirvn — COMMENTED** [review]
So nice to see this shaping up!

File: src/gui/vector/qgsattributesformmodel.h (hunk 8 above)
Comment (gacarrillor) [reply src/gui/vector/qgsattributesformmodel.h]: It's protected to be able to access it directly in subclasses instead of leaving it private and implementing getter/setter for subclasses. Fine for you?

File: src/gui/vector/qgsattributesformmodel.cpp (hunk 27 above)
Comment (gacarrillor) [reply src/gui/vector/qgsattributesformmodel.cpp]: Legacy, I guess from boolean, but better a full name, agree.

File: src/gui/vector/qgsattributesformmodel.cpp (hunk 21 above)
Comment (gacarrillor) [reply src/gui/vector/qgsattributesformmodel.cpp]: [createIndex()](https://doc.qt.io/qt-6/qabstractitemmodel.html#createIndex) expects a pointer to the item for which we'd like the index.

**Comment by gacarrillor** [comment]
> So nice to see this shaping up!

@nirvn, Thank you for the review, all comments addressed.
Note that I've added some commits after your review. Major changes we're before your review, though.

I also updated the PR description.

File: src/gui/vector/qgsattributesformmodel.cpp (hunk 21 above)
Comment (nirvn) [reply src/gui/vector/qgsattributesformmodel.cpp]: Right I mean why are we using childNode here and not parentNode?

Comment (gacarrillor) [reply src/gui/vector/qgsattributesformmodel.cpp]: In that function we're using the `row` and `parent` params to access a specific child, because we're interested in that child's index. 

`parent` lets us access the underlying `parentItem`, from which we can get (using the `row`) the wanted `childItem`, which in turn we pass to `createIndex()` to get its correspondent model index.

**Comment by gacarrillor** [comment]
@nirvn, do you think we can proceed to create the PR in the official QGIS repo in the next days?

File: src/gui/vector/qgsattributesformmodel.cpp (hunk 21 above)
Comment (gacarrillor) [reply src/gui/vector/qgsattributesformmodel.cpp]: Is it clearer now?

**Comment by gacarrillor** [comment]
Rebased!
